version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/film
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=12345
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=film
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    ports:
      - "5432:5432"